# Generated by Django 6.0 on 2025-12-23 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_project'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE orm_project_users RENAME TO orm_project_user;",
                    reverse_sql="ALTER TABLE orm_project_user RENAME TO orm_project_users"
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ProjectUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        # ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.project')),
                    ],
                    options={
                        'db_table': 'orm_project_user',
                    },
                ),
                migrations.AlterField(
                    model_name='project',
                    name='users',
                    field=models.ManyToManyField(through='orm.ProjectUser', to=settings.AUTH_USER_MODEL),
                )
            ],
        ),
        migrations.AddField(
            model_name='projectuser',
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
