# Generated by Django 5.2.8 on 2025-12-26 00:53

import uuid
from django.db import migrations, models

from orm.models import CustomUser


def add_uuid_to_existing_users(apps, schema_editor):
    CustomUser = apps.get_model('orm', 'CustomUser')

    to_update = []

    for user in CustomUser.objects.all():
        user.uuid = uuid.uuid4()
        to_update.append(user)

    CustomUser.objects.bulk_update(to_update, ['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_projectuser_alter_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='customuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(
            add_uuid_to_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
