# Generated by Django 6.0 on 2025-12-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_remove_profile_user_remove_project_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
