# Generated by Django 6.0 on 2025-12-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_customuser_image_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
