# Generated by Django 6.0 on 2025-12-22 01:19

from django.db import migrations

def insert_data(apps, schema_editor):
    ShortURL = apps.get_model("shortener", "ShortURL")
    objects = [
        ShortURL(
            original_url="https://chat.com/",
            code="Chatgpt"
        ),
        ShortURL(
            original_url="https://stackoverflow.com/",
            code="StackOF",
        ),
        ShortURL(
            original_url="https://github.com/",
            code="GitHub",
        ),
    ]
    ShortURL.objects.bulk_create(
        objs=objects, ignore_conflicts=True,
    )

class Migration(migrations.Migration):
    dependencies = [
        ('shortener', '0001_initial'),
    ]

    # 0001 -> 0002
    # 0002 -> 0001 (revert)
    operations = [
        migrations.RunPython(
            insert_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
